### ISSUE TITLE
loading react components from a node module

### ISSUE THREAD

**Issue by JasonStewart1** [reactjs/express-react-views#88] opened 2016-08-01 17:13 UTC
How can i load react components from modules ?

seems like it is not working when i import react components from node modules (jsx and compiled js both).

**Comment by zpao** [comment] 2016-08-01 17:26
It should just work. If you can share a simple repro case I can look into it.

**Comment by JasonStewart1** [comment] 2016-08-01 17:38
App

views/index.jsx

```
var React = require('react');
var test = require ('react-components/src/test');

var HelloMessage = React.createClass({
  render: function() {
    return (
        <div>Hello {this.props.name}</div>
        <NewHelloMessage></NewHelloMessage>
    );
  }
});

module.exports = HelloMessage;
```

node_modules/react-components/src/test.js

```
'use strict';

var React = require('react');

var NewHelloMessage = React.createClass({
    displayName: 'NewHelloMessage',

    render: function render() {
        return React.createElement(
            'div',
            null,
            'New Hello'
        );
    }
});

module.exports = NewHelloMessage;
```

Note: I also tried with jsx instead of js in node module.

**Comment by meister** [comment] 2016-08-04 20:31
@JasonStewart1 Looks like you’re assigning the component to variable `test`, but using `NewHelloMessage` in render, which is probably undefined var, and test is unused.

**Comment by JasonStewart1** [comment] 2016-08-05 17:11
@meister Updated code, I was making a quick repro earlier. 
Still doesn't work.

**Comment by zpao** [comment] 2016-08-05 17:44
Do you see any errors? Can you make a small test repo I could clone to reproduce?

When I try to reproduce I can't.

```sh
git clone # this repo
cd express-react-views/examples/simple
npm i
# put your NewHelloMessage component into node_modules/react-components/test.js
# require('react-components/test') & use in views/index.jsx
npm start
```

I see the test component being rendered.

**Comment by zpao** [comment] 2018-03-03 20:49
Closing since there hasn't been a response from filer in a long time.

**Closed by zpao** 2018-03-03 20:49 UTC
