### ISSUE TITLE
How to load javascript with express-react-views

### ISSUE THREAD

**Issue by moda20** [reactjs/express-react-views#171] opened 2021-08-30 07:55 UTC
Hi, I am trying to add functionalities to my page like pagination on a table and i can't seem to execute javascript code at all.
any function i add to the `onClick` handler is not called. 

here is my definition : 

```
    paginateTo(page, pageSize){
        alert("qsdqsdsq")
        console.log("qsdqdqs");
        this.set
        window.location.href = window.location.pathname + "?page=" + page + "&pageSize=" + pageSize;
    }

<button onClick={()=>this.paginateTo(this.state.pagination?.pageCount,this.state.pagination?.pageSize)} className=""><i
                                            className=""></i></button>
```

i tried with many different solutions like functional component but it didn't change anything.
how am i supposed to load javascript functions in ?

**Comment by hinchley2018** [comment] 2022-01-04 01:23
duplicate of #59 this library renders static content

**Comment by zpao** [comment] 2022-01-06 06:45
This library doesn't make it easy to do what you're looking for, though it's not entirely impossible. But you should probably consider other options like Next or Remix.

**Closed by zpao** 2022-01-06 06:45 UTC
