### ISSUE TITLE
Failed to lookup view in views directory

### ISSUE THREAD

**Issue by rpereira** [reactjs/express-react-views#77] opened 2016-04-30 07:28 UTC
Hi,

I'm experimenting with `express-react-views`, and the view engine is unable to lookup any view.

Here's what I have so far that I find relevant.

```
.
├── config
│   └── application.js
├── app
    └── views
        └── index.jsx
```

``` js
// config/application.js
const Express = require('express');
const path = require('path');

const app = Express();

// React views
app.set('views', path.resolve(__dirname, '../app/views'));
app.set('view engine', 'jsx');
app.engine('jsx', require('express-react-views').createEngine());

app.get('/', function (req, res) {
  res.render('index');
});

app.listen(process.env.PORT, function () {
  console.log('Server listening on port', process.env.PORT);
});
```

``` js
// app/views/index.jsx
import React from 'React';

export default class Index extends React.Component {
  render() {
    return (
      <!doctype html>
      <html>
        <head>
          <meta charset="utf-8" />
          <meta http-equiv="X-UA-Compatible" content="IE=edge" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>Hello!</title>
        </head>
        <body>
        </body>
      </html>
    );
  }
}
```

And here's the error.

```
➔ node config/application.js
Server listening on port 3000
::1 - - [30/Apr/2016:07:17:36 +0000] "GET / HTTP/1.1" 500 1382 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
Error: Failed to lookup view "index" in views directory "/Users/ruipereira/code/deltaworx/webclient/app/views"
    at EventEmitter.render (/Users/ruipereira/code/deltaworx/webclient/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/Users/ruipereira/code/deltaworx/webclient/node_modules/express/lib/response.js:961:7)
    at /Users/ruipereira/code/deltaworx/webclient/config/application.js:23:7
    at Layer.handle [as handle_request] (/Users/ruipereira/code/deltaworx/webclient/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ruipereira/code/deltaworx/webclient/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/ruipereira/code/deltaworx/webclient/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ruipereira/code/deltaworx/webclient/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ruipereira/code/deltaworx/webclient/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/ruipereira/code/deltaworx/webclient/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/ruipereira/code/deltaworx/webclient/node_modules/express/lib/router/index.js:271:10)
```

Am I missing something? I would appreciate any help. CCing @zpao Thanks.

**Comment by zpao** [comment] 2016-04-30 18:03
The `<!doctype>` isn't valid jsx and could be causing a parse issue. Maybe that's just getting swallowed?

**Comment by ruiafonsopereira** [comment] 2016-05-01 09:43
Hi @zpao,

I've removed the `<!doctype>` and the same problem persists.

**Comment by zpao** [comment] 2016-05-02 20:51
I tried to reproduce this and I'm having trouble doing so reliably. I did get it to happen once but not a 2nd time (I did have some babel preset issues though, will need to look into that more). The only way I can repro reliably is if I name the file `index.js` instead of `index.jsx`.

If you had a reproducible test app I could look at, that might be helpful.

**Comment by zpao** [comment] 2016-06-06 17:10
@ruiafonsopereira are you still having issues?

**Comment by ruiafonsopereira** [comment] 2016-06-06 20:40
Hi @zpao,

I had to drop that experiment because I got stuck. If you give me a few days to try and set up a reproducible test app I can get back to you. If you prefer to close this issue in the meantime, go ahead and I'll let you know if the problem persists. 
Thanks.

**Comment by adrianiskandar** [comment] 2016-09-25 22:24
I have the same issue, is not finding the views and  looks like the settings object in options is undefined:

TypeError: Cannot read property 'views' of undefined
    at View.renderFile [as engine] (/projects/modul/node_modules/express-react-views/index.js:38:74)
    at View.render (/projects/modul/node_modules/express/lib/view.js:126:8)
    at tryRender (/projects/modul/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/projects/modul/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/projects/modul/node_modules/express/lib/response.js:960:7)
    at /projects/modul/core/routes/errors.js:27:11
    at Layer.handle_error (/projects/modul/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/projects/modul/node_modules/express/lib/router/index.js:310:13)
    at /projects/modul/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/projects/modul/node_modules/express/lib/router/index.js:330:12)

**Comment by azopyros** [comment] 2017-11-29 23:27
I had it because my index was name `index.js` instead of `index.jsx`.

Because I don't want to have `.jsx` I did this : 

```javascript
    app.set('view engine', 'js')
    app.engine('js', expressReactViews.createEngine({})
```

**Comment by azopyros** [comment] 2017-11-29 23:28
@rpereira have you try `res.render('index.jsx', data)` ?

**Comment by rpereira** [comment] 2017-12-03 08:51
Hi @azopyros. To be honest, I don't remember given it was last year.

**Comment by zpao** [comment] 2018-03-03 20:52
Going to close out since we don't have a reliable repo. Feel free to comment if you work one out and we can revisit.

**Closed by zpao** 2018-03-03 20:52 UTC

**Comment by WinWinHost** [comment] 2019-02-16 00:40
Encountered the same issue today when upgrading my MERN project. 

-Robert Baindourov

**Comment by anoushk1234** [comment] 2021-06-26 10:14
> 
> 
> Encountered the same issue today when upgrading my MERN project.
> 
> -Robert Baindourov
Same here

**Comment by asbjornu** [comment] 2021-07-12 21:37
I have the same issue. When I move the `views` folder to the root, the views are resolved successfully, but when I move `views` into a subfolder, view resolution stops working with the same error message as experienced by @rpereira.

**Comment by carlos-dubon** [comment] 2021-12-04 02:02
For anyone trying to use this with TypeScript just use `express-tsx-views` instead.

[express-tsx-views](https://github.com/pmb0/express-tsx-views#readme)
